# Generated by Django 5.2.12 on 2026-03-27 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0002_note_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="pinned",
            field=models.BooleanField(default=False),
        ),
    ]
