# Generated by Django 5.2.12 on 2026-03-27 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0003_note_pinned"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="color",
            field=models.CharField(default="#FFFF99", max_length=20),
        ),
    ]
